"""Email sender – attaches the Excel report and sends via SMTP."""

import logging
import os
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List

logger = logging.getLogger(__name__)


def send_report(
    xlsx_path: str,
    recipients: List[str],
    smtp_host: str,
    smtp_port: int = 587,
    smtp_user: str = "",
    smtp_password: str = "",
    use_tls: bool = True,
    sender: str = "",
    subject: str = "",
    lookback_days: int = 7,
    total_mem_waste: str = "",
    wasteful_count: int = 0,
) -> None:
    """Send *xlsx_path* as an email attachment to *recipients*."""
    if not recipients:
        raise ValueError("No recipients specified")

    sender = sender or smtp_user
    if not subject:
        from datetime import date
        subject = f"[K8s] Resource Waste Report – {date.today()}"

    body = _build_body(lookback_days, total_mem_waste, wasteful_count, xlsx_path)

    msg = MIMEMultipart()
    msg["From"]    = sender
    msg["To"]      = ", ".join(recipients)
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "html", "utf-8"))

    # Attach Excel file
    with open(xlsx_path, "rb") as f:
        part = MIMEApplication(f.read(), Name=os.path.basename(xlsx_path))
    part["Content-Disposition"] = f'attachment; filename="{os.path.basename(xlsx_path)}"'
    msg.attach(part)

    logger.info("Sending report to %s via %s:%d …", recipients, smtp_host, smtp_port)

    if use_tls:
        with smtplib.SMTP(smtp_host, smtp_port) as srv:
            srv.ehlo()
            srv.starttls()
            if smtp_user and smtp_password:
                srv.login(smtp_user, smtp_password)
            srv.sendmail(sender, recipients, msg.as_bytes())
    else:
        with smtplib.SMTP(smtp_host, smtp_port) as srv:
            if smtp_user and smtp_password:
                srv.login(smtp_user, smtp_password)
            srv.sendmail(sender, recipients, msg.as_bytes())

    logger.info("Email sent successfully to %d recipient(s)", len(recipients))


def _build_body(
    lookback_days: int,
    total_mem_waste: str,
    wasteful_count: int,
    xlsx_path: str,
) -> str:
    from datetime import date
    return f"""
<html><body style="font-family: Arial, sans-serif; color: #222;">
  <h2 style="color:#1F4E79;">☁ Kubernetes Resource Waste Report</h2>
  <p>Date: <b>{date.today()}</b> &nbsp;|&nbsp; Analysis window: <b>{lookback_days} days</b></p>
  <table style="border-collapse:collapse; margin-top:12px;">
    <tr>
      <td style="padding:8px 16px; background:#2E75B6; color:#fff; border-radius:4px 0 0 4px;">
        Over-provisioned workloads
      </td>
      <td style="padding:8px 20px; background:#E8F0FE; font-size:1.3em; font-weight:bold;">
        {wasteful_count}
      </td>
    </tr>
    <tr>
      <td style="padding:8px 16px; background:#C00000; color:#fff; margin-top:4px;">
        Total wasted memory
      </td>
      <td style="padding:8px 20px; background:#FFF0F0; font-size:1.3em; font-weight:bold; color:#C00000;">
        {total_mem_waste}
      </td>
    </tr>
  </table>
  <p style="margin-top:20px; color:#555;">
    Full details are in the attached Excel file:
    <b>{os.path.basename(xlsx_path)}</b>
  </p>
  <hr style="border:none; border-top:1px solid #ddd; margin-top:24px;">
  <p style="font-size:0.8em; color:#999;">
    Generated by k8s-resource-analyzer
  </p>
</body></html>
"""
